// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// accelerations
List accelerations(NumericVector m, NumericMatrix x, NumericMatrix a, double G, double rsmoothsqr);
RcppExport SEXP _nbody_accelerations(SEXP mSEXP, SEXP xSEXP, SEXP aSEXP, SEXP GSEXP, SEXP rsmoothsqrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type rsmoothsqr(rsmoothsqrSEXP);
    rcpp_result_gen = Rcpp::wrap(accelerations(m, x, a, G, rsmoothsqr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nbody_accelerations", (DL_FUNC) &_nbody_accelerations, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_nbody(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
