# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accelerations <- function(m, x, v, a, G, rsmoothsqr, L) {
    .Call('_nbody_accelerations', PACKAGE = 'nbody', m, x, v, a, G, rsmoothsqr, L)
}

energypot <- function(m, x, v, rsmooth) {
    .Call('_nbody_energypot', PACKAGE = 'nbody', m, x, v, rsmooth)
}

