# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accelerations <- function(m, x, G, rsmoothsqr) {
    .Call('_nbody_accelerations', PACKAGE = 'nbody', m, x, G, rsmoothsqr)
}

